version: '3.8'

services:
    client:
        build: ./client
        ports: 
            - "3002:3000"
        environment:
            REACT_APP_API_URL: "http://localhost:4000/"
        volumes:
            - ./client:/app
            - /app/node_modules
    backend:
        build: ./backend
        ports:
            - "4000:4000"
        environment:
            PORT: "4000"
            DB_DATABASE: "mongo"
            DB_HOST: mongo
            DB_USER: "root"
            DB_PASSWORD: "example"
        volumes:
            - ./backend:/app
            - /app/node_modules
    mongo:
        image: "mongo"
        restart: "always"
        volumes:
            - ./database:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "example"
        ports:
            - "27017:27017"
    
        